language: android
jdk:
  - oraclejdk7
android:
  components:
    - android-22            #needed by :app
    - android-7             #needed by :file-explorer
    - build-tools-22.0.1
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew build check
