language: android
sudo: false
jdk:
  - oraclejdk7
env:
  global:
    - MALLOC_ARENA_MAX=2
android:
  components:
    - android-23            #needed by :app
    - android-7             #needed by :file-explorer
    - build-tools-23.0.1
    - sys-img-armeabi-v7a-android-21
    - extra
    - add-on
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew build connectedCheck
