language: android

sudo: false

jdk:
  - oraclejdk7

android:
  components:
    - android-23            #needed by :app
    - android-7             #needed by :file-explorer
    - build-tools-23.0.1
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew build check
