language: android
jdk:
  - oraclejdk7
android:
  components:
    - android-21            #needed by :app
    - android-7             #needed by :file-explorer
    - build-tools-21.1.2

script: ./gradlew build check
