language: android

sudo: required

jdk:
  - oraclejdk8

install:
# Let's use the new command 'sdkmanager' to install Android SDK components
- yes | sdkmanager --verbose "build-tools;27.0.2"
- yes | sdkmanager --verbose "platform-tools"
- yes | sdkmanager --verbose "tools"
- yes | sdkmanager --verbose "platforms;android-24"
- yes | sdkmanager --verbose "system-images;android-24;default;armeabi-v7a"
- yes | sdkmanager --verbose "extras;android;m2repository"
- yes | sdkmanager --verbose "extras;google;m2repository"

# Check tools and dependencies installed
- yes | sdkmanager --list

before_script:
  - echo no | android create avd --force -n test -k "system-images;android-24;default;armeabi-v7a"
  - emulator -avd test -no-audio -no-window
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean assemble --stacktrace
